### ISSUE TITLE
Link broken?

### ISSUE THREAD

**Issue by rajarshimaitra** [0xB10C/bitcoin-development-history#19]
All the links in the doc https://b10c.me/blog/004-the-incomplete-history-of-bitcoin-development/ are opening to a page like this.

![image](https://user-images.githubusercontent.com/36541669/163727691-50d6ddd0-7c93-40d9-97bf-7ea97509daf8.png)

Not sure if that's the intended page or some links are broken..

**Comment by 0xB10C** [comment]
Thanks, I'll have a look why the timeline isn't loading.

**Comment by 0xB10C** [comment]
Thanks, caused by the same problem as #17. I've changed it to load the timeline from https://0xb10c.github.io/bitcoin-development-history/ where GitHub manages the SSL certificate.
